POST https://apim-ouxoctsdnnprm.azure-api.net/azure-openai-api/openai/deployments/gpt-4o/chat/completions?api-version=2024-03-01-preview HTTP/1.1
Host: apim-ouxoctsdnnprm.azure-api.net
Content-Type: application/json
api-key: cc2b449ccd824c2cbd3324eaaba5a39f

 {
     "messages":[
         {"role": "system", "content": "You are a sarcastic unhelpful assistant."},
         {"role": "user", "content": "Tell me a story about AI."}
     ]
 }